### PR TITLE
Add action execution and verify artifact is uploaded

### PR DESCRIPTION
**Pull request by isamadrid90**
Currently, we need to use another project to ensure the action is working correctly. Now, we have a small project inside the `test` folder, and the pull request workflow includes the execution of the action.yml over this project. The goal is to see easily the code changes and ensure that the artifact is correctly uploaded.

### CODE REVIEW

**Comment by isamadrid90** [comment]
🧟‍♀ Mutation Testing Summary ️🧟‍♀️
================================ 
 
 Line Coverage (for mutated classes only): 24/27 (89%) 
 Generated 15 mutations Killed 14 (93%) 
 Mutations with no coverage 1. Test strength 100% 
 Ran 14 tests (0.93 tests per mutation) Enhanced functionality available at https://www.arcmutate.com/ !! The following issues were detected during the run !! Project uses kotlin, but the Arcmutate kotlin plugin is not present (https://docs.arcmutate.com/docs/kotlin.html)
Check artifacts for the complete report

**Comment by isamadrid90** [comment]
🧟‍♀ Mutation Testing Summary ️🧟‍♀️
================================ 
 
 Line Coverage (for mutated classes only): 24/27 (89%) 
 Generated 15 mutations Killed 14 (93%) 
 Mutations with no coverage 1. Test strength 100% 
 Ran 14 tests (0.93 tests per mutation) Enhanced functionality available at https://www.arcmutate.com/ !! The following issues were detected during the run !! Project uses kotlin, but the Arcmutate kotlin plugin is not present (https://docs.arcmutate.com/docs/kotlin.html)
Check artifacts for the complete report

**Comment by isamadrid90** [comment]
🧟‍♀ Mutation Testing Summary ️🧟‍♀️
================================ 
 
 Line Coverage (for mutated classes only): 24/27 (89%) 
 Generated 15 mutations Killed 14 (93%) 
 Mutations with no coverage 1. Test strength 100% 
 Ran 14 tests (0.93 tests per mutation) Enhanced functionality available at https://www.arcmutate.com/ !! The following issues were detected during the run !! Project uses kotlin, but the Arcmutate kotlin plugin is not present (https://docs.arcmutate.com/docs/kotlin.html)
Check artifacts for the complete report

**Comment by isamadrid90** [comment]
🧟‍♀ Mutation Testing Summary ️🧟‍♀️
================================ 
 
 Line Coverage (for mutated classes only): 24/27 (89%) 
 Generated 15 mutations Killed 14 (93%) 
 Mutations with no coverage 1. Test strength 100% 
 Ran 14 tests (0.93 tests per mutation) Enhanced functionality available at https://www.arcmutate.com/ !! The following issues were detected during the run !! Project uses kotlin, but the Arcmutate kotlin plugin is not present (https://docs.arcmutate.com/docs/kotlin.html)
Check artifacts for the complete report

**Review by Aseg — APPROVED** [review]

**Pull request merged**
