### PR TITLE
Remove unnecessary  alerts on action.yml

### PR DESCRIPTION
**Pull request by soaresi2-ppb**
This PR is to remove unnecessary alerts on action like the alerts on this example 
Screenshot 2023-12-18 at 17 39 24

### CODE REVIEW

**Comment by isamadrid90** [comment]
Hello, and thank you for your PR 🎉 

I believe the objective is to remove the text that begins with "Enhance functionality..." Is that correct? In addition, do you have a screenshot that displays what the comment looks like with your modifications? 

Furthermore, I noticed that you removed the emojis from the title. May I ask why you did that?

**Comment by soaresi2-ppb** [comment]
Yes, that's correct.
No, I don't know how to validate this
I removed the emojis because I don't think that make sense use emojis in an action that can be reused by any project. It's only one suggestion.

**Comment by isamadrid90** [comment]
Ok! Let me test it then; I'll document how to do it to make contributing easier.

About the emojis, I'd prefer to keep them, but your point is entirely valid, and I'm going to create an issue to make the title customizable.

**Comment by isamadrid90** [comment]
I checked and the comment looks like the following image, the code removes the *mutations)* could you have a look?
imagen

**Comment by soaresi2-ppb** [comment]
Can you check now?

**Comment by isamadrid90** [comment]
I'm on a trip until 26th, let me get back to you at that date, sorry for the delay.

**Comment by isamadrid90** [comment]
Hello again! Please update your branch with the recent changes in `main`, the action will be executed for the PR automatically, and you will be able to see the result of your changes here.
I hope this is useful for you and makes it easier to contribute to the project :D

**Comment by isamadrid90** [comment]
Mutation Testing Summary
================================ 
 
 Line Coverage (for mutated classes only): 24/27 (89%) 
 Generated 15 mutations Killed 14 (93%) 
 Mutations with no coverage 1. Test strength 100% 
 Ran 14 tests (0.93 tests per mutation)
Check artifacts for the complete report

**Pull request closed without merging**
